unique_name: Training Dimension
object_type: dimension
label: Training Dimension
hierarchies:
  - unique_name: Training Dimension  Hierarchy
    label: Training Dimension  Hierarchy
    levels:
      - unique_name: Employee Number  Level
      - unique_name: Training Level
level_attributes:
  - unique_name: Employee Number  Level
    label: Employee Number  Level
    contains_unique_names: false
    dataset: employee_attrition_fact
    is_unique_key: false
    key_columns:
      - EmployeeNumber
    name_column: EmployeeNumber
  - unique_name: Training Level
    label: Training Level
    contains_unique_names: false
    dataset: employee_attrition_fact
    is_unique_key: false
    key_columns:
      - TrainingTimesLastYear
    name_column: TrainingTimesLastYear
type: standard
